"""
AI Reverse Engineering Module — Parse.bot level
Instead of returning a JSON schema, the LLM generates a full executable
Python function using httpx. This handles complex auth flows, dynamic
tokens, session chaining and pagination automatically.
"""
import json
import logging
import inspect
from typing import Optional
from pydantic import BaseModel, Field
from openai import AsyncOpenAI
import os

from app.config import settings

logger = logging.getLogger(__name__)


class GeneratedEndpoint(BaseModel):
    """Structured output from the LLM that describes the reverse-engineered API."""

    target_url: str = Field(description="The exact undocumented API URL discovered")
    http_method: str = Field(description="HTTP method: GET, POST, etc.")
    required_headers: dict = Field(description="Headers required for auth and content type")
    payload_template: Optional[dict] = Field(default=None, description="JSON body template with {variable} placeholders")
    pagination_param: Optional[str] = Field(default=None, description="Query param name for pagination, if any")
    reasoning: str = Field(description="Clear explanation of how you identified this")
    confidence: float = Field(description="Confidence score 0.0-1.0")

    def to_python_function(self) -> str:
        """
        Renders the schema as a fully self-contained, copy-pasteable Python
        async function using httpx.
        """
        headers_repr = json.dumps(self.required_headers, indent=12)
        payload_repr = json.dumps(self.payload_template, indent=12) if self.payload_template else "None"
        pagination_block = ""
        if self.pagination_param:
            pagination_block = f'\n    if page is not None:\n        params["{self.pagination_param}"] = page\n'

        lines = [
            "import httpx",
            "import asyncio",
            "",
            f"# Auto-generated by HAR Reverse Engineering Platform",
            f"# Target: {self.target_url}",
            f"# Confidence: {self.confidence:.0%}",
            f"# Reasoning: {self.reasoning}",
            "",
            "async def fetch(variables: dict = {}, page=None) -> dict:",
            '    """',
            "    Fetches data from the reverse-engineered internal API.",
            '    """',
            "    import json, copy",
            "",
            f'    url = "{self.target_url}"',
            f"    headers = {json.dumps(self.required_headers)}",
            f"    payload = copy.deepcopy({payload_repr})",
            "    params = {}",
            pagination_block,
            "    if variables:",
            "        url_rendered = url",
            "        for k, v in variables.items():",
            '            url_rendered = url_rendered.replace(f"{{{k}}}", str(v))',
            "        url = url_rendered",
            "        if payload:",
            "            payload_str = json.dumps(payload)",
            "            for k, v in variables.items():",
            '                payload_str = payload_str.replace(f"{{{k}}}", str(v))',
            "            payload = json.loads(payload_str)",
            "",
            "    async with httpx.AsyncClient(timeout=15.0) as client:",
            "        response = await client.request(",
            f'            method="{self.http_method}",',
            "            url=url,",
            "            headers=headers,",
            "            params=params if params else None,",
            "            json=payload,",
            "        )",
            "        response.raise_for_status()",
            "        try:",
            "            return response.json()",
            "        except Exception:",
            '            return {"raw": response.text}',
            "",
            'if __name__ == "__main__":',
            "    result = asyncio.run(fetch())",
            "    import pprint",
            "    pprint.pprint(result)",
        ]
        return "\n".join(lines)


class AIReverseEngineer:
    def __init__(self):
        # Allow DeepSeek fallback via environment variables
        api_key = settings.openai_api_key or os.getenv("DEEPSEEK_API_KEY")
        base_url = None
        
        # Determine base URL if it's DeepSeek
        if api_key and (api_key.startswith("sk-") and "deepseek" in os.getenv("OPENAI_MODEL", "")):
            base_url = "https://api.deepseek.com"
        elif not settings.openai_api_key and os.getenv("DEEPSEEK_API_KEY"):
            base_url = "https://api.deepseek.com"

        self.client = AsyncOpenAI(api_key=api_key, base_url=base_url)
        self.model = os.getenv("OPENAI_MODEL") or ("deepseek-chat" if base_url else settings.openai_model)

    async def identify_api(self, distilled_har: list, goal: str) -> GeneratedEndpoint:
        """
        Sends token-efficient HAR data to the LLM and parses the JSON response.
        Works across standard LLMs (OpenAI, DeepSeek, etc).
        """
        schema_json = GeneratedEndpoint.model_json_schema()
        
        system_prompt = (
            "You are an elite backend reverse-engineer. You will receive a minified HAR log "
            "and a goal. Identify the single most specific internal API request that satisfies the goal. "
            "Prefer JSON/GraphQL endpoints over HTML endpoints. "
            "Identify all headers required to reproduce the request including auth tokens and cookies.\n\n"
            "CRITICAL: You must return a strict JSON object that perfectly matches the following schema. "
            "Do NOT wrap it in markdown block quotes. Respond ONLY with valid JSON.\n\n"
            f"Schema: {json.dumps(schema_json, indent=2)}"
        )

        n_entries = len(distilled_har)
        logger.info(f"Sending {n_entries} HAR entries to LLM ({self.model}) for analysis...")

        completion = await self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": (
                        f"Goal: {goal}\n\n"
                        f"HAR Log:\n{json.dumps(distilled_har, indent=2)}"
                    ),
                },
            ],
            response_format={"type": "json_object"},
        )

        content = completion.choices[0].message.content
        logger.info(f"Received JSON block: {content[:200]}...")
        
        try:
            result = GeneratedEndpoint.model_validate_json(content)
        except Exception as e:
            logger.error(f"Failed to parse LLM response: {content}")
            raise ValueError(f"LLM did not conform to schema: {e}")

        logger.info(
            f"LLM identified endpoint: {result.http_method} {result.target_url} "
            f"(confidence={result.confidence:.0%})"
        )
        return result
